package com.asiainfo.general.dao;

import com.asiainfo.general.model.UserVO;
import com.asiainfo.general.model.UserVOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("userVOMapper")
public interface UserVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int countByExample(UserVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int deleteByExample(UserVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int insert(UserVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int insertSelective(UserVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    List<UserVO> selectByExample(UserVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    UserVO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserVO record, @Param("example") UserVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int updateByExample(@Param("record") UserVO record, @Param("example") UserVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int updateByPrimaryKeySelective(UserVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Fri May 06 14:41:59 CST 2016
     */
    int updateByPrimaryKey(UserVO record);
}